export const BORROWED_ITEM_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  IN_POSSESSION: "IN_POSSESSION",
  CANCELLED: "CANCELLED",
  DISAPPROVED: "DISAPPROVED",
  UNRELEASED: "UNRELEASED",
  RETURNED: "RETURNED",
  UNRETURNED: "UNRETURNED",
  DAMAGED_BUT_REPAIRABLE: "DAMAGED_BUT_REPAIRABLE",
  UNREPAIRABLE: "UNREPAIRABLE",
  LOST: "LOST",
};

export const ACTIVE_BORROWED_ITEM_STATUSES = {
  PENDING_APPROVAL: BORROWED_ITEM_STATUS.PENDING_APPROVAL,
  APPROVED: BORROWED_ITEM_STATUS.APPROVED,
  IN_POSSESSION: BORROWED_ITEM_STATUS.IN_POSSESSION,
} as const;

export const COMPLETE_BORROWED_ITEM_STATUSES = {
  RETURNED: BORROWED_ITEM_STATUS.RETURNED,
  UNRETURNED: BORROWED_ITEM_STATUS.UNRETURNED,
  DAMAGED_BUT_REPAIRABLE: BORROWED_ITEM_STATUS.DAMAGED_BUT_REPAIRABLE,
  UNREPAIRABLE: BORROWED_ITEM_STATUS.UNREPAIRABLE,
  LOST: BORROWED_ITEM_STATUS.LOST,
} as const;

export const UNRETURNED_BORROWED_ITEM_STATUSES = {
  UNRETURNED: BORROWED_ITEM_STATUS.UNRETURNED,
  DAMAGED_BUT_REPAIRABLE: BORROWED_ITEM_STATUS.DAMAGED_BUT_REPAIRABLE,
  UNREPAIRABLE: BORROWED_ITEM_STATUS.UNREPAIRABLE,
  LOST: BORROWED_ITEM_STATUS.LOST,
} as const;

export const COMPLETE_BORROWED_ITEM_COMBOBOX_OPTIONS = [
  {
    value: BORROWED_ITEM_STATUS.RETURNED,
    label: "Returned",
  },
  {
    value: BORROWED_ITEM_STATUS.UNRETURNED,
    label: "Unreturned",
  },
  {
    value: BORROWED_ITEM_STATUS.DAMAGED_BUT_REPAIRABLE,
    label: "Damaged but repairable",
  },
  {
    value: BORROWED_ITEM_STATUS.UNREPAIRABLE,
    label: "Unrepairable",
  },
  {
    value: BORROWED_ITEM_STATUS.LOST,
    label: "Lost",
  },
];
